---
- name: Configure and deploy NGINX web server
  hosts: webserver
  become: yes

  vars_files:
  - ../group_vars/webserver.yml

  roles:
    - common
    - users
    - ufw
    - fail2ban
    - nginx
    - webapp



